import jsPDF from 'jspdf'
import { formatMoney } from './format'
import { useAuthStore } from '../stores/auth'

// Generate a clean A4 invoice PDF and trigger a browser download.
// Pure-client (no server roundtrip), uses the user's currency preference.
export function downloadInvoicePdf(invoice) {
  const auth = useAuthStore()
  const issuer = auth.user?.name || 'Freelancer'
  const issuerEmail = auth.user?.email || ''

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()

  const VIOLET = [124, 58, 237]
  const SLATE_900 = [15, 23, 42]
  const SLATE_700 = [51, 65, 85]
  const SLATE_500 = [100, 116, 139]
  const SLATE_300 = [203, 213, 225]
  const EMERALD = [16, 185, 129]
  const ROSE = [225, 29, 72]
  const AMBER = [217, 119, 6]

  // ----- Header band -----
  doc.setFillColor(...VIOLET)
  doc.rect(0, 0, W, 90, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  doc.text('INVOICE', 40, 56)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text('Sushmi MCP', W - 40, 38, { align: 'right' })
  doc.setFontSize(8)
  doc.text('Freelance Intelligence Platform', W - 40, 52, { align: 'right' })

  // ----- Invoice meta -----
  let y = 130

  doc.setTextColor(...SLATE_500)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('INVOICE NUMBER', 40, y)
  doc.text('ISSUED', 220, y)
  doc.text('DUE', 360, y)

  doc.setTextColor(...SLATE_900)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text(String(invoice.id || ''), 40, y + 18)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(invoice.issuedDate || '—', 220, y + 18)
  doc.text(invoice.dueDate || '—', 360, y + 18)

  // status pill
  const status = invoice.status || 'Pending'
  const pillColor = status === 'Paid' ? EMERALD : status === 'Overdue' ? ROSE : AMBER
  const pillX = W - 40 - 80
  const pillY = y + 4
  doc.setFillColor(...pillColor)
  doc.roundedRect(pillX, pillY, 80, 22, 11, 11, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text(status.toUpperCase(), pillX + 40, pillY + 15, { align: 'center' })

  // separator
  y += 50
  doc.setDrawColor(...SLATE_300)
  doc.setLineWidth(0.5)
  doc.line(40, y, W - 40, y)

  // ----- Bill From / Bill To -----
  y += 24
  doc.setTextColor(...SLATE_500)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('FROM', 40, y)
  doc.text('BILL TO', W / 2 + 10, y)

  doc.setTextColor(...SLATE_900)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(issuer, 40, y + 18)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...SLATE_700)
  if (issuerEmail) doc.text(issuerEmail, 40, y + 34)

  doc.setTextColor(...SLATE_900)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(invoice.client || '—', W / 2 + 10, y + 18)

  // ----- Line items table -----
  y += 80
  doc.setFillColor(248, 250, 252)
  doc.rect(40, y, W - 80, 32, 'F')
  doc.setTextColor(...SLATE_500)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('DESCRIPTION', 56, y + 20)
  doc.text('AMOUNT', W - 56, y + 20, { align: 'right' })

  y += 32

  // Single line item (we don't have line-item granularity yet)
  doc.setTextColor(...SLATE_900)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  const description = invoice.description || `Professional services — ${invoice.client || 'engagement'}`
  doc.text(description, 56, y + 24)
  doc.text(formatMoney(invoice.amount || 0), W - 56, y + 24, { align: 'right' })

  // separator under items
  y += 50
  doc.setDrawColor(...SLATE_300)
  doc.line(40, y, W - 40, y)

  // ----- Totals -----
  y += 30
  doc.setTextColor(...SLATE_500)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text('Subtotal', W - 200, y)
  doc.setTextColor(...SLATE_900)
  doc.text(formatMoney(invoice.amount || 0), W - 56, y, { align: 'right' })

  y += 18
  doc.setTextColor(...SLATE_500)
  doc.text('Tax', W - 200, y)
  doc.setTextColor(...SLATE_900)
  doc.text(formatMoney(0), W - 56, y, { align: 'right' })

  // total band
  y += 24
  doc.setFillColor(...SLATE_900)
  doc.roundedRect(W - 240, y - 4, 200, 38, 8, 8, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('TOTAL DUE', W - 224, y + 20)
  doc.setFontSize(14)
  doc.text(formatMoney(invoice.amount || 0), W - 56, y + 22, { align: 'right' })

  // ----- Footer -----
  doc.setTextColor(...SLATE_500)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('Thank you for your business.', 40, H - 60)
  doc.setFontSize(8)
  doc.text('Generated by Sushmi MCP — sushmi-mcp.vercel.app', 40, H - 44)
  doc.text(`Generated ${new Date().toISOString().slice(0, 10)}`, W - 40, H - 44, { align: 'right' })

  doc.save(`${invoice.id || 'invoice'}.pdf`)
}
